//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartForDevice
    {
        public int PartForDeviceId { get; set; }
        public string PartName { get; set; }
        public string PartImage { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int ContactId { get; set; }
        public int CategoryId { get; set; }
        public string partStatus { get; set; }
        public string partLocationCity { get; set; }
        public string partLocationState { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
    }
}
